=== vanhouc/vanhouc-final/Instruments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Instruments" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Instruments">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="Instrument " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAC3mvu6yzsGRpfCTI8NaNTcAAAAAC3pFLRwUONABAAAAHiN5wdJAG4A
cwB0AHIAdQBtAGUAbgB0AHMAAAAAAAAAnF1VxsjUbUeOzAVQ+hl+wwcAAAC3mvu6
yzsGRpfCTI8NaNTcSQBuAHMAdAByAHUAbQBlAG4AdAAAAAAAAAAauumjOd1vSYLN
fWgm4In1BwAAALea+7rLOwZGl8JMjw1o1NxUAHkAcABlAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAMAAAABAAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="t5r7uss7BkaXwkyPDWjU3A==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Instrument" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1560"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Common name of musical instrument"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="16"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Type" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1290"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Orchestral section for this instrument"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="16"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== vanhouc/vanhouc-final/Instruments.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Instruments.xsd" generated="2013-04-22T15:16:07">
<Instruments>
<Instrument>Baritone</Instrument>
<Type>Brass</Type>
</Instruments>
<Instruments>
<Instrument>Bass Clarinet</Instrument>
<Type>Woodwind</Type>
</Instruments>
<Instruments>
<Instrument>Bass Drum</Instrument>
<Type>Percussion</Type>
</Instruments>
<Instruments>
<Instrument>Bassoon</Instrument>
<Type>Woodwind</Type>
</Instruments>
<Instruments>
<Instrument>Castanets</Instrument>
<Type>Percussion</Type>
</Instruments>
<Instruments>
<Instrument>Cello</Instrument>
<Type>String</Type>
</Instruments>
<Instruments>
<Instrument>Chimes</Instrument>
<Type>Percussion</Type>
</Instruments>
<Instruments>
<Instrument>Clarinet</Instrument>
<Type>Woodwind</Type>
</Instruments>
<Instruments>
<Instrument>Contrabassoon</Instrument>
<Type>Woodwind</Type>
</Instruments>
<Instruments>
<Instrument>Cymbals</Instrument>
<Type>Percussion</Type>
</Instruments>
<Instruments>
<Instrument>Double Bass</Instrument>
<Type>String</Type>
</Instruments>
<Instruments>
<Instrument>English Horn</Instrument>
<Type>Woodwind</Type>
</Instruments>
<Instruments>
<Instrument>Euphonium</Instrument>
<Type>Brass</Type>
</Instruments>
<Instruments>
<Instrument>Flute</Instrument>
<Type>Woodwind</Type>
</Instruments>
<Instruments>
<Instrument>French Horn</Instrument>
<Type>Brass</Type>
</Instruments>
<Instruments>
<Instrument>Glockenspiel</Instrument>
<Type>Percussion</Type>
</Instruments>
<Instruments>
<Instrument>Guiro</Instrument>
<Type>Percussion</Type>
</Instruments>
<Instruments>
<Instrument>Harp</Instrument>
<Type>String</Type>
</Instruments>
<Instruments>
<Instrument>Oboe</Instrument>
<Type>Woodwind</Type>
</Instruments>
<Instruments>
<Instrument>Piccolo</Instrument>
<Type>Woodwind</Type>
</Instruments>
<Instruments>
<Instrument>Saxophone</Instrument>
<Type>Woodwind</Type>
</Instruments>
<Instruments>
<Instrument>Snare Drum</Instrument>
<Type>Percussion</Type>
</Instruments>
<Instruments>
<Instrument>Tambourine</Instrument>
<Type>Percussion</Type>
</Instruments>
<Instruments>
<Instrument>Timpani</Instrument>
<Type>Percussion</Type>
</Instruments>
<Instruments>
<Instrument>Triangle</Instrument>
<Type>Percussion</Type>
</Instruments>
<Instruments>
<Instrument>Trombone</Instrument>
<Type>Brass</Type>
</Instruments>
<Instruments>
<Instrument>Trumpet</Instrument>
<Type>Brass</Type>
</Instruments>
<Instruments>
<Instrument>Tuba</Instrument>
<Type>Brass</Type>
</Instruments>
<Instruments>
<Instrument>Viola</Instrument>
<Type>String</Type>
</Instruments>
<Instruments>
<Instrument>Violin</Instrument>
<Type>String</Type>
</Instruments>
<Instruments>
<Instrument>Xylophone</Instrument>
<Type>Percussion</Type>
</Instruments>
</dataroot>
